name: CI

on:
  push:
    branches: [ test_ci ]
    
  workflow_dispatch:

jobs:
  env:
    job_var: hello_from_job_level
    
  build:
    env:
      build_only_var: hello_from_build
      runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: List all ORIGINAL files
        run: ls

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Run Python Script
        run: python create_file.py

      - name: List all NEW files
        run: ls

      - name: print a value
        run: |
          echo "step_var: $step_var"
          echo "job_var: $job_var"
          echo "build_only_var: $build_only_var"

  display:
    runs-on: ubuntu-latest
    needs: build
    if: always()
    
    steps:
      - name: print a value
        run: |
          echo "step_var: $step_var"
          echo "job_var: $job_var"
          echo "build_only_var: $build_only_var"
          echo "step_var: ${{ env.step_var }}"
          echo "job_var: ${{ env.job_var }}"
        env:
          step_var: hello_from_step
